login:
    path: /login
    controller: App\Controller\SecurityController::login

logout:
    path: /login    

admin:
    path: /admin
    controller: App\Controller\DefaultController::admin

driver:
    path: /driver
    controller: App\Controller\DefaultController::driver

register:
    path: /register
    controller: App\Controller\RegistrationController::registerAdmin
    
#site seasiren
home:
    path: /
    controller: App\Controller\SeasirenController::home

translation:
   path: /translation/{lang}/{page}
   controller: App\Controller\SeasirenController::userTranslation